version: "2.0"
services:
  db:
    image: mysql:5.6
    env_file: 
      - ./desenv 
    volumes:
      - ./data/mysql:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    env_file:
      - ./desenv
    ports:
      - 8084:80
    volumes:
      - ./data/wordpress:/var/www/html
